

function EatSomething()
    Citizen.CreateThread(function()
        rUtils.PlayAnim('mp_player_inteat@burger', 'mp_player_int_eat_burger_fp', 49, 8.0, -8.0)
        Citizen.Wait(3000)
        ClearPedSecondaryTask(pPed)
    end)
end


function Drink()
    Citizen.CreateThread(function()
        rUtils.PlayAnim('mp_player_intdrink', 'loop_bottle', 49, 1.0, -1.0, 1, 2000)
        Citizen.Wait(3000)
        ClearPedSecondaryTask(pPed)
    end)
end 

function HealPlayer()
    TriggerEvent("rF:AddThirst", 100)
    TriggerEvent("rF:AddHunger", 100)
    SetEntityHealth(pPed, 200.0)
end

RegisterCommand("heal", function(source, args, rawCommand)
    if pGroup ~= "user" then
        HealPlayer()
    end
end, false)


RegisterNetEvent("core:DringWater")
AddEventHandler("core:DringWater", function()
    TriggerEvent("rF:AddThirst", 60)
    TriggerEvent("rF:RemoveHunger", 5)
    TriggerServerEvent(events.remove, token, "Bouteille d'eau", 1) 
    Drink()
end)

RegisterNetEvent("core:DringCoka")
AddEventHandler("core:DringCoka", function()
    TriggerEvent("rF:AddThirst", 15)
    TriggerEvent("rF:RemoveHunger", 5)
    TriggerServerEvent(events.remove, token, "Canette de coca", 1)
    Drink()
end)

RegisterNetEvent("core:EatPizza")
AddEventHandler("core:EatPizza", function()
    TriggerEvent("rF:AddHunger", 50)
    TriggerEvent("rF:RemoveThirst", 10)
    TriggerServerEvent(events.remove, token, "Pizza simple", 1)
    EatSomething()
end)

RegisterNetEvent("core:EatPizzaFromage")
AddEventHandler("core:EatPizzaFromage", function()
    TriggerEvent("rF:AddHunger", 60)
    TriggerEvent("rF:RemoveThirst", 20)
    TriggerServerEvent(events.remove, token, "Pizza 3 fromages", 1)
    EatSomething()
end)

RegisterNetEvent("core:EatChips")
AddEventHandler("core:EatChips", function()
    TriggerEvent("rF:AddHunger", 10)
    TriggerEvent("rF:RemoveThirst", 5)
    TriggerServerEvent(events.remove, token, "Chips", 1)
    EatSomething()
end)


RegisterNetEvent("core:EatSandwichSimple")
AddEventHandler("core:EatSandwichSimple", function()
    TriggerEvent("rF:AddHunger", 40)
    TriggerEvent("rF:RemoveThirst", 10)
    TriggerServerEvent(events.remove, token, "Sandwich simple", 1)
    EatSomething()
end)

RegisterNetEvent("core:EatSandwichPoulet")
AddEventHandler("core:EatSandwichPoulet", function()
    TriggerEvent("rF:AddHunger", 60)
    TriggerEvent("rF:RemoveThirst", 20)
    TriggerServerEvent(events.remove, token, "Sandwich poulet: César (halal)", 1)
    EatSomething()
end)

RegisterNetEvent("core:EatSandwichThon")
AddEventHandler("core:EatSandwichThon", function()
    TriggerEvent("rF:AddHunger", 50)
    TriggerEvent("rF:RemoveThirst", 15)
    TriggerServerEvent(events.remove, token, "Sandwich Thon (Le pécheur)", 1)
    EatSomething()
end)

RegisterNetEvent("core:EatSandwichVegan")
AddEventHandler("core:EatSandwichVegan", function()
    TriggerEvent("rF:AddHunger", 40)
    TriggerEvent("rF:RemoveThirst", 10)
    TriggerServerEvent(events.remove, token, "Sandwich vegan (Veggie)", 1)
    EatSomething()
end)

RegisterNetEvent("core:EatSandwichSaucisson")
AddEventHandler("core:EatSandwichSaucisson", function()
    TriggerEvent("rF:AddHunger", 70)
    TriggerEvent("rF:RemoveThirst", 30)
    TriggerServerEvent(events.remove, token, "Sandwich saucisson: (Le frenchie)", 1)
    EatSomething()
end)

RegisterNetEvent("core:EatHotDog")
AddEventHandler("core:EatHotDog", function()
    TriggerEvent("rF:AddHunger", 50)
    TriggerEvent("rF:RemoveThirst", 5)
    TriggerServerEvent(events.remove, token, "Hotdog simple", 1)
    EatSomething()
end)

RegisterNetEvent("core:EatTacos")
AddEventHandler("core:EatTacos", function()
    TriggerEvent("rF:AddHunger", 60)
    TriggerEvent("rF:RemoveThirst", 10)
    TriggerServerEvent(events.remove, token, "Tacos", 1)
    EatSomething()
end)

RegisterNetEvent("core:EatKebab")
AddEventHandler("core:EatKebab", function()
    TriggerEvent("rF:AddHunger", 70)
    TriggerEvent("rF:RemoveThirst", 15)
    TriggerServerEvent(events.remove, token, "Kebab", 1)
    EatSomething()
end)


RegisterNetEvent("core:EatPatte")
AddEventHandler("core:EatPatte", function()
    TriggerEvent("rF:AddHunger", 60)
    TriggerEvent("rF:RemoveThirst", 10)
    TriggerServerEvent(events.remove, token, "Pasta Bolognese", 1)
    EatSomething()
end)


RegisterNetEvent("core:UseWeed")
AddEventHandler("core:UseWeed", function()
    PlayUrl("weed", "https://www.youtube.com/watch?v=zvEJu3VPE9A", 0.3, false)
    TriggerServerEvent(events.remove, token, "Canabis de bonne qualité", 1)
    StartScreenEffect("ChopVision", 0, 0)
    Wait(1*60000)
    Destroy("weed")
    StopScreenEffect("ChopVision")
end)